version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"  # Vite development server
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3001"  # JSON server
    volumes:
      - ./server:/app/server
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 